#!/bin/bash

# Function to print the start and end markers for a file
print_file_markers() {
    local file="$1"
    echo "### Start \"$file\""
    cat "$file"
    echo "### End \"$file\""
}

# Function to check if a file should be processed
should_process_file() {
    local file="$1"
    local script_filename="$(basename "$0")"
    local current_filename="$(basename "$file")"
    [[ -f "$file" && ! "$file" =~ ^\..* && "$current_filename" != "$script_filename" ]]
}

process_directory_recursive() {
    local dir="$1"
    
    for item in "$dir"/*; do
        if [[ -d "$item" ]]; then
            process_directory_recursive "$item"
        elif should_process_file "$item"; then
            print_file_markers "$item"
        fi
    done
}

recursive=false

if [[ "$1" == "-r" ]]; then
    recursive=true
    shift
fi

if [[ "$#" -eq 0 ]]; then
    directory="$(pwd)"
else
    directory="$1"
fi

if [[ -d "$directory" ]]; then
    if [[ "$recursive" == "true" ]]; then
        process_directory_recursive "$directory"
    else
        for file in "$directory"/*; do
            if should_process_file "$file"; then
                print_file_markers "$file"
            fi
        done
    fi
else
    echo "Error: \"$directory\" is not a valid directory."
    exit 1
fi
